services:
  backend:
    build: .
    ports:
      - "8000:8000"
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/project/
    environment:
      - SECRET_KEY=test
      - DEBUG=TRUE