services:
  backend:
    build: .
    ports:
      - "8000:8000"
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/project/
    environment:
      - SECRET_KEY=test
      - DEBUG=TRUE
    depends_on:
      - redis

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:v3
    restart: always
    depends_on:
      - backend
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5001:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      # Uncomment to customise these settings

      #Specifies the virtual path from web server root where SMTP4DEV web interface will be hosted. e.g. "/" or "/smtp4dev"
      #- ServerOptions__BasePath=/smtp4dev

      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker:
    container_name: worker
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend/:/project

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler


    depends_on:
      - worker
      - redis
      - backend
    volumes:
      - ./backend/:/project


volumes:
  smtp4dev-data: