# Generated by Django 4.2.1 on 2023-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appBlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
