# Generated by Django 4.2.1 on 2023-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='asus1.png', upload_to=''),
        ),
    ]
