# Generated by Django 4.2.1 on 2023-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='appBlog/posts/images/'),
        ),
    ]
