# Generated by Django 4.2.1 on 2023-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appBlog", "0008_category_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                db_table="appBlog_post_category", to="appBlog.category"
            ),
        ),
    ]
