# Generated by Django 4.2.1 on 2023-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
