# Generated by Django 3.2.22 on 2023-10-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAccount', '0003_alter_profile_user'),
        ('appBlog', '0014_comment_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAccount.profile'),
        ),
    ]
