# Generated by Django 4.2.1 on 2023-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appTodo", "0002_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("done", "done"), ("undone", "undone")],
                default="undone",
                max_length=6,
            ),
        ),
    ]
